2022-01-15 14:26:39,614 INFO    MainThread:150345 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:26:39,615 INFO    MainThread:150345 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:26:39,615 INFO    MainThread:150345 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142639-1lyi9vi3/logs/debug.log
2022-01-15 14:26:39,615 INFO    MainThread:150345 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142639-1lyi9vi3/logs/debug-internal.log
2022-01-15 14:26:39,616 INFO    MainThread:150345 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:26:39,616 INFO    MainThread:150345 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:26:39,617 INFO    MainThread:150345 [wandb_init.py:init():460] starting backend
2022-01-15 14:26:39,617 INFO    MainThread:150345 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:26:39,627 INFO    MainThread:150345 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:26:39,629 INFO    MainThread:150345 [backend.py:ensure_launched():221] started backend process with pid: 150381
2022-01-15 14:26:39,629 INFO    MainThread:150345 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:26:39,631 INFO    MainThread:150345 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:26:39,640 INFO    MainThread:150345 [wandb_init.py:init():563] communicating current version
2022-01-15 14:26:40,050 INFO    MainThread:150345 [wandb_init.py:init():568] got version response 
2022-01-15 14:26:40,051 INFO    MainThread:150345 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:26:40,281 INFO    MainThread:150345 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:26:40,877 INFO    MainThread:150345 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:26:40,878 INFO    MainThread:150345 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:26:40,878 INFO    MainThread:150345 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:26:40,879 INFO    MainThread:150345 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:26:40,879 INFO    MainThread:150345 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:26:42,331 INFO    MainThread:150345 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:26:42,331 INFO    MainThread:150345 [wandb_run.py:_restore():1752] restore
2022-01-15 14:26:44,391 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:26:44,684 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:26:45,302 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 4655
}

2022-01-15 14:26:45,405 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:26:45,512 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:26:45,614 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:45,717 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:45,821 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:45,923 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:46,026 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:46,521 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:26:46,774 INFO    MainThread:150345 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}
local_info {
}

2022-01-15 14:26:47,840 INFO    MainThread:150345 [wandb_run.py:_append_files():2180] logging synced files
