2022-01-15 14:20:01,847 INFO    MainThread:146592 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:20:01,847 INFO    MainThread:146592 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:20:01,847 INFO    MainThread:146592 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/download/wandb/run-20220115_142001-2jg1kuxo/logs/debug.log
2022-01-15 14:20:01,847 INFO    MainThread:146592 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/download/wandb/run-20220115_142001-2jg1kuxo/logs/debug-internal.log
2022-01-15 14:20:01,848 INFO    MainThread:146592 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:20:01,848 INFO    MainThread:146592 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:20:01,849 INFO    MainThread:146592 [wandb_init.py:init():460] starting backend
2022-01-15 14:20:01,849 INFO    MainThread:146592 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:20:01,855 INFO    MainThread:146592 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:20:01,856 INFO    MainThread:146592 [backend.py:ensure_launched():221] started backend process with pid: 146621
2022-01-15 14:20:01,856 INFO    MainThread:146592 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:20:01,857 INFO    MainThread:146592 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:20:01,863 INFO    MainThread:146592 [wandb_init.py:init():563] communicating current version
2022-01-15 14:20:02,226 INFO    MainThread:146592 [wandb_init.py:init():568] got version response 
2022-01-15 14:20:02,226 INFO    MainThread:146592 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:20:02,390 INFO    MainThread:146592 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:20:02,920 INFO    MainThread:146592 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:20:02,920 INFO    MainThread:146592 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:20:02,921 INFO    MainThread:146592 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:20:02,921 INFO    MainThread:146592 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:20:02,921 INFO    MainThread:146592 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:20:05,629 INFO    MainThread:146592 [wandb_run.py:finish():1457] finishing run mdunford/exercise_14/2jg1kuxo
2022-01-15 14:20:05,629 INFO    MainThread:146592 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:20:05,629 INFO    MainThread:146592 [wandb_run.py:_restore():1752] restore
2022-01-15 14:20:07,931 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2022-01-15 14:20:08,294 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2022-01-15 14:20:08,418 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 3922
}

2022-01-15 14:20:08,521 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 3922
}

2022-01-15 14:20:08,625 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 3922
}

2022-01-15 14:20:08,727 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:08,830 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:08,934 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:09,037 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:09,140 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:09,825 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:20:10,086 INFO    MainThread:146592 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}
local_info {
}

2022-01-15 14:20:11,144 INFO    MainThread:146592 [wandb_run.py:_append_files():2180] logging synced files
