2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142257-3a7dqq1s/logs/debug.log
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142257-3a7dqq1s/logs/debug-internal.log
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:22:57,140 INFO    MainThread:147726 [wandb_init.py:init():460] starting backend
2022-01-15 14:22:57,140 INFO    MainThread:147726 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:22:57,147 INFO    MainThread:147726 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:22:57,148 INFO    MainThread:147726 [backend.py:ensure_launched():221] started backend process with pid: 147762
2022-01-15 14:22:57,149 INFO    MainThread:147726 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:22:57,150 INFO    MainThread:147726 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:22:57,158 INFO    MainThread:147726 [wandb_init.py:init():563] communicating current version
2022-01-15 14:22:57,582 INFO    MainThread:147726 [wandb_init.py:init():568] got version response 
2022-01-15 14:22:57,582 INFO    MainThread:147726 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:22:57,751 INFO    MainThread:147726 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:22:58,328 INFO    MainThread:147726 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:22:58,328 INFO    MainThread:147726 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:22:58,328 INFO    MainThread:147726 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:22:58,329 INFO    MainThread:147726 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:22:58,329 INFO    MainThread:147726 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:22:59,923 INFO    MainThread:147726 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:22:59,924 INFO    MainThread:147726 [wandb_run.py:_restore():1752] restore
2022-01-15 14:23:02,357 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:23:02,583 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:23:02,775 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 4655
}

2022-01-15 14:23:02,878 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:23:02,982 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:23:03,085 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:03,189 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:03,292 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:03,412 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:03,515 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:04,009 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:23:04,320 INFO    MainThread:147726 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}
local_info {
}

2022-01-15 14:23:05,380 INFO    MainThread:147726 [wandb_run.py:_append_files():2180] logging synced files
