2022-01-15 14:20:12,388 INFO    MainThread:146770 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:20:12,388 INFO    MainThread:146770 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:20:12,388 INFO    MainThread:146770 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142012-3v5rgqcg/logs/debug.log
2022-01-15 14:20:12,388 INFO    MainThread:146770 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_142012-3v5rgqcg/logs/debug-internal.log
2022-01-15 14:20:12,389 INFO    MainThread:146770 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:20:12,389 INFO    MainThread:146770 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:20:12,389 INFO    MainThread:146770 [wandb_init.py:init():460] starting backend
2022-01-15 14:20:12,389 INFO    MainThread:146770 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:20:12,397 INFO    MainThread:146770 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:20:12,399 INFO    MainThread:146770 [backend.py:ensure_launched():221] started backend process with pid: 146806
2022-01-15 14:20:12,400 INFO    MainThread:146770 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:20:12,402 INFO    MainThread:146770 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:20:12,412 INFO    MainThread:146770 [wandb_init.py:init():563] communicating current version
2022-01-15 14:20:12,818 INFO    MainThread:146770 [wandb_init.py:init():568] got version response 
2022-01-15 14:20:12,818 INFO    MainThread:146770 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:20:13,111 INFO    MainThread:146770 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:20:13,680 INFO    MainThread:146770 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:20:13,681 INFO    MainThread:146770 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:20:13,681 INFO    MainThread:146770 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:20:13,682 INFO    MainThread:146770 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:20:13,682 INFO    MainThread:146770 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:20:15,265 INFO    MainThread:146770 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:20:15,267 INFO    MainThread:146770 [wandb_run.py:_restore():1752] restore
2022-01-15 14:20:17,698 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:20:17,905 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:20:18,140 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:20:18,242 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:20:18,345 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 4629
  total_bytes: 5302
}

2022-01-15 14:20:18,449 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:18,552 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:18,655 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:18,758 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:18,861 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:19,247 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:20:19,499 INFO    MainThread:146770 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}
local_info {
}

2022-01-15 14:20:20,556 INFO    MainThread:146770 [wandb_run.py:_append_files():2180] logging synced files
