2022-01-15 14:16:01,127 INFO    MainThread:144472 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:16:01,127 INFO    MainThread:144472 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:16:01,127 INFO    MainThread:144472 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/download/wandb/run-20220115_141601-2r439t6n/logs/debug.log
2022-01-15 14:16:01,127 INFO    MainThread:144472 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/download/wandb/run-20220115_141601-2r439t6n/logs/debug-internal.log
2022-01-15 14:16:01,128 INFO    MainThread:144472 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:16:01,129 INFO    MainThread:144472 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:16:01,129 INFO    MainThread:144472 [wandb_init.py:init():460] starting backend
2022-01-15 14:16:01,130 INFO    MainThread:144472 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:16:01,143 INFO    MainThread:144472 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:16:01,144 INFO    MainThread:144472 [backend.py:ensure_launched():221] started backend process with pid: 144501
2022-01-15 14:16:01,144 INFO    MainThread:144472 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:16:01,145 INFO    MainThread:144472 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:16:01,149 INFO    MainThread:144472 [wandb_init.py:init():563] communicating current version
2022-01-15 14:16:01,522 INFO    MainThread:144472 [wandb_init.py:init():568] got version response 
2022-01-15 14:16:01,522 INFO    MainThread:144472 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:16:01,812 INFO    MainThread:144472 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:16:02,288 INFO    MainThread:144472 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:16:02,288 INFO    MainThread:144472 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:16:02,288 INFO    MainThread:144472 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:16:02,289 INFO    MainThread:144472 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:16:02,289 INFO    MainThread:144472 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:16:04,668 INFO    MainThread:144472 [wandb_run.py:finish():1457] finishing run mdunford/exercise_14/2r439t6n
2022-01-15 14:16:04,668 INFO    MainThread:144472 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:16:04,668 INFO    MainThread:144472 [wandb_run.py:_restore():1752] restore
2022-01-15 14:16:06,805 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2022-01-15 14:16:07,013 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2022-01-15 14:16:07,847 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 3922
}

2022-01-15 14:16:07,949 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 3922
}

2022-01-15 14:16:08,051 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:08,154 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:08,258 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:08,363 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:08,466 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:08,570 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:09,179 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}

2022-01-15 14:16:09,436 INFO    MainThread:144472 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3922
  total_bytes: 3922
}
local_info {
}

2022-01-15 14:16:10,491 INFO    MainThread:144472 [wandb_run.py:_append_files():2180] logging synced files
