2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_141730-3r42g18l/logs/debug.log
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_141730-3r42g18l/logs/debug-internal.log
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:17:30,497 INFO    MainThread:145721 [wandb_init.py:init():460] starting backend
2022-01-15 14:17:30,497 INFO    MainThread:145721 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:17:30,503 INFO    MainThread:145721 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:17:30,505 INFO    MainThread:145721 [backend.py:ensure_launched():221] started backend process with pid: 145775
2022-01-15 14:17:30,506 INFO    MainThread:145721 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:17:30,507 INFO    MainThread:145721 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:17:30,516 INFO    MainThread:145721 [wandb_init.py:init():563] communicating current version
2022-01-15 14:17:30,914 INFO    MainThread:145721 [wandb_init.py:init():568] got version response 
2022-01-15 14:17:30,915 INFO    MainThread:145721 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:17:31,212 INFO    MainThread:145721 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:17:31,788 INFO    MainThread:145721 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:17:31,788 INFO    MainThread:145721 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:17:31,789 INFO    MainThread:145721 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:17:31,790 INFO    MainThread:145721 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:17:31,790 INFO    MainThread:145721 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:17:33,268 INFO    MainThread:145721 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:17:33,269 INFO    MainThread:145721 [wandb_run.py:_restore():1752] restore
2022-01-15 14:17:35,302 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:17:35,614 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:17:36,226 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 4629
}

2022-01-15 14:17:36,329 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:17:36,437 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:17:36,540 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5129
  total_bytes: 5302
}

2022-01-15 14:17:36,643 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:36,746 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:36,850 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:36,953 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:37,057 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:37,353 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:17:37,661 INFO    MainThread:145721 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}
local_info {
}

2022-01-15 14:17:38,723 INFO    MainThread:145721 [wandb_run.py:_append_files():2180] logging synced files
