2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_143719-29a3t6o1/logs/debug.log
2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/preprocess/wandb/run-20220115_143719-29a3t6o1/logs/debug-internal.log
2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:37:19,157 INFO    MainThread:153645 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:37:19,158 INFO    MainThread:153645 [wandb_init.py:init():460] starting backend
2022-01-15 14:37:19,158 INFO    MainThread:153645 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:37:19,163 INFO    MainThread:153645 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:37:19,165 INFO    MainThread:153645 [backend.py:ensure_launched():221] started backend process with pid: 153695
2022-01-15 14:37:19,166 INFO    MainThread:153645 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:37:19,167 INFO    MainThread:153645 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:37:19,175 INFO    MainThread:153645 [wandb_init.py:init():563] communicating current version
2022-01-15 14:37:19,618 INFO    MainThread:153645 [wandb_init.py:init():568] got version response 
2022-01-15 14:37:19,618 INFO    MainThread:153645 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:37:19,867 INFO    MainThread:153645 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:37:20,431 INFO    MainThread:153645 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:37:20,431 INFO    MainThread:153645 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:37:20,431 INFO    MainThread:153645 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:37:20,432 INFO    MainThread:153645 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:37:20,432 INFO    MainThread:153645 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:37:21,927 INFO    MainThread:153645 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-15 14:37:21,927 INFO    MainThread:153645 [wandb_run.py:_restore():1752] restore
2022-01-15 14:37:23,957 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:37:24,273 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 1085
}

2022-01-15 14:37:24,881 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:37:24,984 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:37:25,087 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1085
  total_bytes: 5302
}

2022-01-15 14:37:25,191 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:25,294 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:25,398 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:25,519 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:25,622 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:26,114 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}

2022-01-15 14:37:26,369 INFO    MainThread:153645 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5302
  total_bytes: 5302
}
local_info {
}

2022-01-15 14:37:27,426 INFO    MainThread:153645 [wandb_run.py:_append_files():2180] logging synced files
