2022-01-15 14:38:24,127 INFO    MainThread:154685 [wandb_setup.py:_flush():71] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2022-01-15 14:38:24,127 INFO    MainThread:154685 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 14:38:24,127 INFO    MainThread:154685 [wandb_init.py:_log_setup():371] Logging user logs to /home/marc/development/python/udacity_course/genre_classification/starter/evaluate/wandb/run-20220115_143824-15pe9hq0/logs/debug.log
2022-01-15 14:38:24,128 INFO    MainThread:154685 [wandb_init.py:_log_setup():372] Logging internal logs to /home/marc/development/python/udacity_course/genre_classification/starter/evaluate/wandb/run-20220115_143824-15pe9hq0/logs/debug-internal.log
2022-01-15 14:38:24,129 INFO    MainThread:154685 [wandb_init.py:init():404] calling init triggers
2022-01-15 14:38:24,129 INFO    MainThread:154685 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-15 14:38:24,129 INFO    MainThread:154685 [wandb_init.py:init():460] starting backend
2022-01-15 14:38:24,130 INFO    MainThread:154685 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 14:38:24,135 INFO    MainThread:154685 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 14:38:24,137 INFO    MainThread:154685 [backend.py:ensure_launched():221] started backend process with pid: 154721
2022-01-15 14:38:24,138 INFO    MainThread:154685 [wandb_init.py:init():469] backend started and connected
2022-01-15 14:38:24,140 INFO    MainThread:154685 [wandb_init.py:init():533] updated telemetry
2022-01-15 14:38:24,149 INFO    MainThread:154685 [wandb_init.py:init():563] communicating current version
2022-01-15 14:38:24,534 INFO    MainThread:154685 [wandb_init.py:init():568] got version response 
2022-01-15 14:38:24,534 INFO    MainThread:154685 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 14:38:24,794 INFO    MainThread:154685 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 14:38:25,541 INFO    MainThread:154685 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 14:38:25,542 INFO    MainThread:154685 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 14:38:25,542 INFO    MainThread:154685 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 14:38:25,543 INFO    MainThread:154685 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-15 14:38:25,543 INFO    MainThread:154685 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 14:38:26,739 INFO    MainThread:154685 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-15 14:38:26,741 INFO    MainThread:154685 [wandb_run.py:_restore():1752] restore
2022-01-15 14:38:29,073 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 862
}

2022-01-15 14:38:29,399 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 862
}

2022-01-15 14:38:29,822 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 11329
}

2022-01-15 14:38:29,925 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 862
  total_bytes: 11329
}

2022-01-15 14:38:30,028 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5973
  total_bytes: 11329
}

2022-01-15 14:38:30,135 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7382
  total_bytes: 11329
}

2022-01-15 14:38:30,238 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:30,340 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:30,443 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:30,546 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:30,650 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:30,932 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}

2022-01-15 14:38:31,333 INFO    MainThread:154685 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11329
  total_bytes: 11329
}
local_info {
}

2022-01-15 14:38:32,396 INFO    MainThread:154685 [wandb_run.py:_append_files():2180] logging synced files
